# This file was generated by GoReleaser. DO NOT EDIT.
cask "stacktower" do
  version "1.6.1"

  on_macos do
    on_intel do
      sha256 "25c2ed2c8d7166ac6354d43bac239a7a6010d8619a0ee2ce47752f1d1848d540"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "74a3f512d8f504e7ab22ca237cec8735c200a0500d08b47729cd854ac82d08a9"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dc0a0f3940f03a2fafa783b67035f40a174425fed2bd75905edeb611b4d080f1"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2232344ddd36b9db946995b6a9cd49f864cdcec07e66dbf08dc7cd62ac2adf03"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "stacktower"
  desc "Visualize dependency graphs as elegant stacked tower diagrams"
  homepage "https://github.com/stacktower-io/stacktower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stacktower"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stacktower"]
    end
  end

  # No zap stanza required

end
