# This file was generated by GoReleaser. DO NOT EDIT.
cask "stacktower" do
  version "1.6.3"

  on_macos do
    on_intel do
      sha256 "f0d46843cab173874e74f91ec40fafe0d4898eba3227e297779aef1084bc13ab"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ec085316d2acceb6fa746995e93ceecd9e40172198d213d2928f8c028f6490a5"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4d411fab034d8008a93591038c8d9e034098ec328a2ffae4f90b409b55ed83f"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c0b2f26d3ede5f92aa61a696be48fc0503f05fc82ddef562791220185f48eaee"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "stacktower"
  desc "Visualize dependency graphs as elegant stacked tower diagrams"
  homepage "https://github.com/stacktower-io/stacktower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stacktower"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stacktower"]
    end
  end

  # No zap stanza required

end
