# This file was generated by GoReleaser. DO NOT EDIT.
cask "stacktower" do
  version "1.6.4"

  on_macos do
    on_intel do
      sha256 "e0c64e357ce28905f6e45982592f3372a3a9c29dc1690c11e30e605c768b4b36"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "45dc46f67a7bb93520a1cb4585a50880913ea5a4a98d11afdddd800a79c25226"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ecb9e943dd62e5a6eac220bf15de38e5de0d1bebc21d563d3b1c2f8b1a260e4e"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4efea15f4c3cf2574505b2ccb66a9bd1b315c9572b1a1d4f73c6f45aa83e4230"
      url "https://github.com/stacktower-io/stacktower/releases/download/v#{version}/stacktower_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "stacktower"
  desc "Visualize dependency graphs as elegant stacked tower diagrams"
  homepage "https://github.com/stacktower-io/stacktower"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stacktower"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stacktower"]
    end
  end

  # No zap stanza required

end
