# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacktower < Formula
  desc "Visualize dependency graphs as elegant "stack tower" diagrams"
  homepage "https://github.com/matzehuels/stacktower"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "26bceb4a90e8addbbfbda669980134c7b435820bb9c6a690a3a514600e4ee26a"

      def install
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Darwin_arm64.tar.gz"
      sha256 "54c196ddce9b25e1856fcdae2eabdb3fadbbd4b8690951b1c47ad3ea58ec0b1d"

      def install
        bin.install "stacktower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Linux_x86_64.tar.gz"
      sha256 "cb2fec7b35d2844c693caa2a4f897c8e404c14569ec10ea4fa61e0926520ef66"
      def install
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Linux_arm64.tar.gz"
      sha256 "30a5571335af93728378393ed511dbe03503c8547e297db2e1fada09885cb970"
      def install
        bin.install "stacktower"
      end
    end
  end

  test do
    system "#{bin}/stacktower", "--version"
  end
end
