# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacktower < Formula
  desc "Visualize dependency graphs as elegant stacked tower diagrams"
  homepage "https://github.com/matzehuels/stacktower"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "06994fd632674d3ff02565ebd782541d7ef972072e28284d8ca309098c618277"

      def install
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Darwin_arm64.tar.gz"
      sha256 "95e283c6ae0d02d052f6e6f8461081005a79dae1aa0d621bb10c3ad3e8b12ec8"

      def install
        bin.install "stacktower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Linux_x86_64.tar.gz"
      sha256 "2ea24fc7e0bf20e6331c7658ba02922d5f2295586a8fe5f92b5a901582ff105b"
      def install
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Linux_arm64.tar.gz"
      sha256 "cd9d5ebc11800744a47ef2cfc0b9e95f0d544fec813a40c5aef4ad509c0343d1"
      def install
        bin.install "stacktower"
      end
    end
  end

  test do
    system "#{bin}/stacktower", "--version"
  end
end
