# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacktower < Formula
  desc "Visualize dependency graphs as elegant stacktower diagrams"
  homepage "https://github.com/matzehuels/stacktower"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "b34930f901fbdc4db34d051aee68a29049a1f4c5985e1a91e3e08f72fe68dc76"

      def install
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Darwin_arm64.tar.gz"
      sha256 "69f8677737c9927de18ef816b9e75e5a22286462df80080684756f4b6185c179"

      def install
        bin.install "stacktower"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Linux_x86_64.tar.gz"
      sha256 "065a3fcc752a4ac2b209022a4a07ddf9c5f55d975cf21c8070944b79abcfa316"
      def install
        bin.install "stacktower"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matzehuels/stacktower/releases/download/v0.1.0/stacktower_0.1.0_Linux_arm64.tar.gz"
      sha256 "1993266c4fb33c87f4c96cb793f5f6bf815a3caf0c621f3403bf44f1bc8c2b6a"
      def install
        bin.install "stacktower"
      end
    end
  end

  test do
    system "#{bin}/stacktower", "--version"
  end
end
